---
title: "Skills and Honors"
---

# Skills

## Computational skills

-   Data processing tool: R, SAS, Julia, Python, JMP, SQL
-   Editorial tool: GitHub, GitLab, LaTeX, Markdown, VS code, WordPress, OJS
-   Microsoft office package: Power BI, Word, Excel, Power, Outlook
-   Image tool: Photoshop, ChenDraw
-   Others: Command-line environment

## Analytical techniques

-   Spectroscopy: UV-Vis, FT-IR
-   Chromatography: GPC, HPLC, GC-MS, IC
-   Thermal analysis: TGA, DSC, DMA
-   Microscopy: SEM, AFM, TEM, Optical Microscopy
-   X-ray: WAXD, SAXS
-   Viscosity: Rheometer
-   Paper and water properties analysis

# Teaching
 
-   STAT 2215Q-003\
    *Introduction to Statistics II*, Spring 2024
-   STAT 1100Q-021D\
    *Elementary Concepts of Statistics*, Fall 2023
-   STAT 3375Q-004D\
    *Introduction to Mathematical Statistics*, Fall 2023

# Awards and Scholarships

+ Mu Sigma Rho, 2021-present
+ University Graduate Research Assistantship, 2013-2016
+ Second-class Study Scholarship, 2007-2008
+ Second-class Study Scholarship and Diathesis Developing Scholarship, 2006-2007
+ Third-class Study Scholarship and Diathesis Developing Scholarship, 2005-2006



# Conference Presentations

+ "Emergency Department and Hospital Use among Cognitively Vulnerable Medicare Advantage Enrollees" 
Gerontological Society of America (GSA) 2024 Annual Scientific Meeting. 
Seattle, WA. November 13-16, 2024 (oral and poster).

+ “Cellulose nanocrystals containing lignin as additive and reinforcing agent in melt-spinning of
polypropylene” 251 th American Chemical Society National Meeting. San Diego, CA. March, 2016
(oral).


+ “Lignin contained nanocellulose as additive and reinforcing agent in melt-spinning of polyethylene
and polypropylene” IAB Meeting. Raleigh, NC. November, 2015 (oral and poster)


+ “Nanocellulose as additive and reinforcing agent in melt-spinning of polyethylene and
polypropylene_with pre-compounding” IAB Meeting. Raleigh, NC. May, 2015 (oral and poster)


+ “Cellulose nanocrystals as additive and reinforcing agent in melt-spinning of polypropylene” 249 th
American Chemical Society National Meeting. Denver, CO. March, 2015 (oral).


+ “Nanocellulose as additive and reinforcing agent in melt-spinning of polyethylene and
polypropylene_without pre-compounding” IAB Meeting. Raleigh, NC. November, 2014 (oral and
poster)


+ “Cellulose nanocrystals as additive and reinforcing agent in melt-spinning of polypropylene”
Textile North America. Atlanta, GA. May, 2014 (poster).


+ “Cellulose nanocrystals as additive and reinforcing agent in polyethylene and polypropylene
films_compatibility improvement” IAB Meeting. Raleigh, NC. May, 2014 (oral and poster)


+ “Thermoplastic matrix reinforced with lignocellulose nanofibrils (LCNF): effect of lignin content”.
247 th American Chemical Society National Meeting. Dallas, TX. April, 2014 (poster).


+ “Cellulose nanocrystals as additive and reinforcing agent in polyethylene and polypropylene films”
IAB Meeting. Raleigh, NC. November, 2013 (oral and poster)


+ “Cellulose nanocrystals as additive and reinforcing agent in melt-spinning of polyethylene and
polypropylene_ cellulose nanocrystals production and surface modification” IAB Meeting.
Raleigh, NC. May, 2013 (oral and poster)


+ “Effect of metal ions and wood pitch on paper properties”, 16 th International Symposium on
Wood, Fiber and Pulping Chemistry (ISWFPC), Tianjin, China, 2011 (poster)


